### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "validPassword123"
}

### Create a new user, invalid body
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": null,
  "password": "validPassword123"
}
