### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "validPassword123"
}

### Create a new user, invalid body
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": null,
  "password": "validPassword123"
}

### Find a user with a given id
GET http://localhost:3000/auth/4

### suppose not to find anything
GET http://localhost:3000/auth/999

### Find users with a given email
GET http://localhost:3000/auth?email=test@test.com

### ain't suppose not to find nutin'
GET http://localhost:3000/auth?email=numberTwo@test.com

### Delete a user of a given id
DELETE  http://localhost:3000/auth/4

### Update a user's email fo a given id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
  "email": "updatedEmail@test.com"
}

### Update a user's password fo a given id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
  "password": "updatedQwerty"
}